spring.application.name=users-api

server.port=8080


#-----H2 Database-------
spring.datasource.url=jdbc:h2:mem:oauth2db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#----console------
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


#---JWT--------
#   15 min
#   7 days
app.jwt.secret=5A7134743777217A25432A46294A404E635266556A586E327235753878
app.jwt.access-token-expiry-ms=900000
app.jwt.refresh-token-expiry-ms=604800000

#----OAUTH2 REDIRECT-----
app.auth2.redirect-uri=http://localhost:8080/auth/success

# ── OAUTH2 SOCIAL LOGIN ───────────────────────────────────────────

spring.security.oauth2.client.registration.google.client-id=GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.github.client-id=GITHUB_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=GITHUB_CLIENT_SECRET
spring.security.oauth2.client.registration.github.scope=user:email,read:user

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false