spring.application.name=users-api

server.port=8080


#-----H2 Database-------
spring.datasource.url=jdbc:h2:mem:oauth2db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#----console------
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


#---JWT--------
app.jwt.secret=5A7134743777217A25432A46294A404E635266556A586E327235753878
app.jwt.access-token-expiry-ms=900000   #15 min
app.jwt.refresh-token-expiry-ms=604800000   #7 days